# Generated by Django 4.2.4 on 2023-10-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=30)),
                ('Std', models.CharField(default='', max_length=5)),
                ('Father_name', models.CharField(default='', max_length=30)),
                ('City', models.CharField(default='', max_length=15, null=True)),
                ('Contact', models.CharField(default='', max_length=10, null=True)),
                ('Dob', models.DateField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Image')),
                ('Registered', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
