# Generated by Django 4.2.4 on 2023-11-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Performance',
            field=models.CharField(default='Good', max_length=10),
        ),
    ]
