# Generated by Django 4.2.4 on 2023-11-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=150, null=True)),
                ('option1', models.CharField(default='', max_length=100, null=True)),
                ('option2', models.CharField(default='', max_length=100, null=True)),
                ('option3', models.CharField(default='', max_length=100, null=True)),
                ('answer', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
    ]
