# Generated by Django 4.2.4 on 2023-11-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, null=True)),
                ('parent_name', models.CharField(default='', max_length=30, null=True)),
                ('city', models.CharField(default='Jaipur', max_length=20, null=True)),
                ('salary', models.CharField(default='', max_length=6, null=True)),
                ('role', models.CharField(default='', max_length=10, null=True)),
                ('registered', models.DateField(auto_now_add=True)),
                ('contact', models.CharField(default='', max_length=10, null=True)),
            ],
        ),
    ]
