# Generated by Django 4.2.4 on 2023-12-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdeatils',
            name='education_1_end',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='educationdeatils',
            name='education_1_start',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='educationdeatils',
            name='education_2_end',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='educationdeatils',
            name='education_2_start',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='experience_1_end',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='experience_1_start',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='experience_2_end',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='experience_2_start',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
